apiVersion: hyperspike.io/v1
kind: Valkey
metadata:
  name: {{ include "valkey-cluster.fullname" . }}
  labels:
  {{- include "valkey-cluster.labels" . | nindent 4 }}
spec:
  volumePermissions: {{ .Values.spec.volumePermissions }}
  nodes: {{ .Values.spec.nodes }}
