apiVersion: v2
name: kafka-operator-resources
description: Deploy Kafka resources for Strimzi Kafka operator

sources:
- https://github.com/oicr-softeng/helm-charts/tree/main/kafka-operator-resources

type: application

version: 0.5.0

appVersion: "3.7.1"
