entityOperator:
  networkPolicy:
    create: false
    egress: []
    ingress: []

Kafka:
  config:
    default.replication.factor: 3
    min.insync.replicas: 3
    offsets.topic.replication.factor: 3
    transaction.state.log.min.isr: 3
    transaction.state.log.replication.factor: 3
  listeners: {}
  spec:
    kafka:
      metadataVersion: 4.2-IV1
      version: 4.2.0

kafkaBridge:
  enabled: false
  networkPolicy:
    create: false
    egress: []
    ingress: []

kafkaMode: kraft

KafkaNodePool:
  replicas: 3
  storage:
    deleteClaim: false
    size: 10Gi
  template:
    kafkaContainer:
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
    pod:
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
    # external:
    #   name: external
    #   port: 19092
    #   tls: false

networkPolicyPeers: []
  # - podSelector:
  #     matchLabels:
  #       app.kubernetes.io/instance: kafka-client
