{{- if and .Values.network.ingress .Values.network.gateway -}}
{{- fail "network.ingress and network.gateway cannot both be configured" -}}
{{- end -}}
{{- if .Values.network.ingress -}}
{{- $fullName := include "stateless-svc.fullname" . -}}
{{- $svcPortName := .Values.service.portName -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "stateless-svc.labels" . | nindent 4 }}
    {{- include "stateless-svc.customLabels" . | nindent 4 }}
  {{- with .Values.network.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.network.ingress.className }}
  ingressClassName: {{ .Values.network.ingress.className }}
  {{- end }}
  {{- if .Values.network.ingress.tls }}
  tls:
    {{- range .Values.network.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.network.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if .pathType }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  name: {{ $svcPortName }}
          {{- end }}
    {{- end }}
{{- end }}
