apiVersion: v2
name: valkey-cluster
description: Deploy a Valkey cluster using the hyperspike.io operator

sources:
- https://github.com/oicr-softeng/helm-charts/tree/main/valkey-cluster

type: application

version: 0.4.0

appVersion: "0.1.0"
